<?php
return [
    'tables' => [
        'posts' => [
            'mandante',
            'title',
            'titleSlug',
            'description',
            'hint',
            'file',
            'file1',
            'file2',
            'file3',
            'file4',
            'file5',
            'file6',
            'file7',
            'file8',
            'file9',
            'file10',
            'file11',
            'file12',
            'file13',
            'file14',
            'file15',
            'paramProfileImageSize',
            'paramProfileImageX',
            'paramProfileImageY',
            'paramName',
            'paramFirstName',
            'paramNameSize',
            'paramNameColor',
            'paramNameX',
            'paramNameY',
        ],
    ],
];